Python 3.12.0rc1 (v3.12.0rc1:63bcd91dac, Aug  5 2023, 10:33:00) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.

============ RESTART: /Users/p53/Documents/GitHub/-puzzle.py/main.py ===========
Hi, PyCharm
>>> #!/usr/bin/env python3
... """
... You found the hidden challenge. Nice.
... 
... This is part of the application process. The goal is not to prove that you can
... do cryptography by hand. The goal is to show curiosity, follow-through, basic
... technical fluency, and clear written communication.
... 
... What to do next:
... 
... 1. Save this decoded file as:
... 
...      puzzle.py
... 
... 2. Create a small public GitHub repository.
... 
... 3. Add this file to the repository as:
... 
...      puzzle.py
... 
... 4. Run the script from your terminal using your real name:
... 
...      DONT_PANIC=1 python3 puzzle.py --candidate "Your Name"
... 
...   Example:
... 
...      DONT_PANIC=1 python3 puzzle.py --candidate "Jane Applicant"
... 
... 5. Add a README.md to your repository that includes:
... 
...   - A short explanation of how you found the hidden challenge
...   - How you decoded the original string
...   - What this script does
...   - The command you ran
...   - The exact output you received
...   - The final decrypted answer
...   - Any tools you used, including AI tools
... 
